<a href="https://colab.research.google.com/github/makhmudjumanazarov/deep_learning/blob/main/tensorflow_basics_for_me.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np 

In [5]:
import tensorflow as tf         

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [27]:
print(tf.__version__)  

2.9.2


In [28]:
hello = tf.constant('Hello  World')

In [29]:
hello 


<tf.Tensor 'Const:0' shape=() dtype=string>

In [30]:
print(hello)  

Tensor("Const:0", shape=(), dtype=string)


In [31]:
type(hello)    

tensorflow.python.framework.ops.Tensor

In [32]:
x = tf.constant(100)

In [33]:
x

<tf.Tensor 'Const_1:0' shape=() dtype=int32>

In [34]:
print(x)   

Tensor("Const_1:0", shape=(), dtype=int32)


In [35]:
x = x + 100

In [36]:
print(x)       

Tensor("add:0", shape=(), dtype=int32)


In [37]:
sess = tf.Session()       

In [39]:
print(sess.run(hello)) 

b'Hello  World'


In [25]:
hello 

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello  World'>

In [40]:
type(sess.run(hello))  

bytes

In [41]:
sess.run(x)  

200

In [42]:
type(sess.run(x))  

numpy.int32

In [43]:
x = tf.constant(2)
y = tf.constant(3)

In [44]:
sess.run(x + y) 

5

In [49]:
with tf.Session() as sess:
  print("Constantlar bilan operations")
  print('Addition', sess.run(x + y))
  print('Subtraction', sess.run(x - y))
  print('Multiplication', sess.run(x * y))
  print('Division', sess.run(x/y)) 
  print('Division', sess.run(x//y))  

Constantlar bilan operations
Addition 5
Subtraction -1
Multiplication 6
Division 0.6666666666666666
Division 0


In [50]:
x = tf.placeholder(tf.float32, shape=(1024, 1024))

In [51]:
x 

<tf.Tensor 'Placeholder:0' shape=(1024, 1024) dtype=float32>

In [64]:
x = tf.placeholder(tf.int32)
y = tf.placeholder(tf.int32)

In [63]:
x 

<tf.Tensor 'Placeholder_5:0' shape=<unknown> dtype=int32>

In [58]:
x = tf.placeholder(tf.int64)  

In [55]:
x 

<tf.Tensor 'Placeholder_2:0' shape=<unknown> dtype=int64>

In [59]:
type(x)

tensorflow.python.framework.ops.Tensor

In [60]:
print(x)

Tensor("Placeholder_4:0", dtype=int64)


In [72]:
add = tf.add(x,y)
sub = tf.subtract(x,y)
mul = tf.multiply(x,y)

In [73]:
d = {x:20, y:30}

In [74]:
with tf.Session() as sess:
    print('Operations with Constants')
    print('Addition',sess.run(add,feed_dict=d))
    print('Subtraction',sess.run(sub,feed_dict=d))
    print('Multiplication',sess.run(mul,feed_dict=d))

Operations with Constants
Addition 50
Subtraction -10
Multiplication 600


In [75]:
import numpy as np

In [76]:
a = np.array([[5.0, 5.0]])
b = np.array([[2.0], [2.0]])

In [77]:
a 

array([[5., 5.]])

In [78]:
b

array([[2.],
       [2.]])

In [79]:
a.shape

(1, 2)

In [80]:
b.shape

(2, 1)

In [81]:
mat1 = tf.constant(a)

In [82]:
mat1

<tf.Tensor 'Const_4:0' shape=(1, 2) dtype=float64>

In [83]:
mat2 = tf.constant(b)

In [84]:
matrix_multi = tf.matmul(mat1, mat2)  

In [85]:
matrix_multi 

<tf.Tensor 'MatMul:0' shape=(1, 1) dtype=float64>

In [87]:
with tf.Session()  as sess:
  result = sess.run(matrix_multi)
  print(result) 

[[20.]]
